<div align="center"> 

### Hi there 👋
  
![Soph's GitHub stats](https://github-readme-stats.vercel.app/api?username=sophiaiscoding&show_icons=true&theme=radical)
<br/>
[![wakatime](https://wakatime.com/badge/user/4c5cb9d9-5a47-4fe6-b372-61702cd1a94a.svg)](https://wakatime.com/@4c5cb9d9-5a47-4fe6-b372-61702cd1a94a)
</div>


<!-- - 🔭 I’m currently working on Marketing 
- 🌱 I’m currently learning ...
- 👯 I’m looking to collaborate ...
- 🤔 I’m looking for help with ...
- 💬 Ask me about ...
- 📫 How to reach me: ...
- 😄 Pronouns: she/her
- ⚡ Fun fact: ...
-->
